Repository terraform-providers/terraform-provider-docker, pull requests merged in 2018-10, with the labels that each got.

#89 [fix-documentation-ports] only one port has to be set
  website/docs/r/container.html.markdown
Labels: documentation, size/XS

#95 fixes ports on containers
  CHANGELOG.md
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  website/docs/r/container.html.markdown
Labels: size/L

#96 Adds pid and namespace mode
  CHANGELOG.md
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  website/docs/r/container.html.markdown
Labels: enhancement, size/S

#97 Image can be pulled with its repo digest
  CHANGELOG.md
  docker/resource_docker_image_funcs.go
  docker/resource_docker_image_test.go
  website/docs/r/image.html.markdown
Labels: size/S

#101 docker_container external port default value aligned with documentation
  CHANGELOG.md
  docker/resource_docker_container.go
  docker/resource_docker_container_test.go
Labels: size/XS

#103 Random external port for containers
  CHANGELOG.md
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  scripts/runAccTests.sh
  website/docs/r/container.html.markdown
Labels: bug, size/L

#92 Add labels to support docker stacks
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_network.go
  docker/resource_docker_network_funcs.go
  docker/resource_docker_network_test.go
  docker/resource_docker_secret.go
  docker/resource_docker_secret_test.go
  docker/resource_docker_volume.go
  docker/resource_docker_volume_test.go
  website/docs/r/network.html.markdown
  website/docs/r/secret.html.markdown
  website/docs/r/volume.html.markdown
Labels: size/L

#50 Add ip address of each network to the computed attributes
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  website/docs/r/container.html.markdown
Labels: enhancement

#106 Add rm and attach options to execute short-lived containers
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  website/docs/r/container.html.markdown
Labels: enhancement, size/XL

#49 Simplify the image options parser.
  docker/resource_docker_image_funcs.go
  docker/resource_docker_image_funcs_test.go
Labels: enhancement
