Repository terraform-providers/terraform-provider-docker, pull requests merged in 2018-05, with the labels that each got.

#40 Feat/swarm 4 new resources
  .travis.yml
  README.md
  docker/provider.go
  docker/resource_docker_config.go
  docker/resource_docker_config_test.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_image_funcs.go
  docker/resource_docker_secret.go
  docker/resource_docker_secret_test.go
  docker/resource_docker_service.go
  docker/resource_docker_service_funcs.go
  docker/resource_docker_service_test.go
  docker/resource_docker_volume.go
  docker/structures_service.go
  docker/validators.go
  docker/validators_test.go
  scripts/runAccTests.sh
  scripts/testing/server_v3.js
  vendor/github.com/gogo/protobuf/LICENSE~HEAD
  vendor/golang.org/x/sys/LICENSE~HEAD
  website/docker.erb
  website/docs/r/config.html.markdown
  website/docs/r/secret.html.markdown
  website/docs/r/service.html.markdown
Labels: enhancement

#66 Fix service flatteners
  docker/resource_docker_service.go
  docker/resource_docker_service_funcs.go
  docker/resource_docker_service_test.go
  docker/structures_service.go
Labels: bug

#47 Adds warning about the link feature
  docker/resource_docker_container.go
  website/docs/r/container.html.markdown
Labels: documentation

#68 Update/docker-18-03-1
  .travis.yml
  CHANGELOG.md
  docker/resource_docker_service.go
  docker/resource_docker_service_funcs.go
  docker/structures_service.go
  website/docs/r/service.html.markdown
Labels: enhancement
