Repository terraform-providers/terraform-provider-docker, pull requests merged in 2019-10, with the labels that each got.

#192 Support for group-add
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  website/docs/r/container.html.markdown
Labels: documentation, size/M

#190 Add `shm_size' attribute for `docker_container' resource.
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  website/docs/r/container.html.markdown
Labels: documentation, size/XS

#189 Minor docker_service documentation fix
  website/docs/r/service.html.markdown
Labels: documentation, size/XS

#188 Allow docker_registry_image to read from AWS ECR registry
  docker/data_source_docker_registry_image.go
  docker/data_source_docker_registry_image_test.go
Labels: size/S

#193 fix: service env truncation for multiple delimiters
  docker/resource_docker_service_test.go
  docker/structures_service.go
Labels: size/XS

#194 fix: binary upload as base 64 content
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  website/docs/r/container.html.markdown
Labels: documentation, size/L

#207 Updated logdrivers list
  docker/resource_docker_container.go
Labels: size/XS

#202 [work in progress] CI revamp
  .go-version
  .travis.yml
  README.md
Labels: size/M

#209 Remove logging drivers white-list
  docker/resource_docker_container.go
  docker/resource_docker_service.go
Labels: size/XS

#206 Add support for readonly containers
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  website/docs/r/container.html.markdown
Labels: documentation, size/S
