Repository terraform-providers/terraform-provider-docker, pull requests merged in 2019-05, with the labels that each got.

#143 Fixes for image pulling and local registry
  docker/data_source_docker_registry_image_test.go
  docker/provider.go
  docker/provider_test.go
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  docker/resource_docker_image_funcs.go
  docker/resource_docker_image_test.go
  docker/resource_docker_service.go
  docker/resource_docker_service_funcs.go
  docker/resource_docker_service_test.go
  go.mod
  go.sum
  scripts/runAccTests.sh
  scripts/testing/dockerconfig.json
  scripts/testing/setup_private_registry.sh
  vendor/github.com/docker/docker-credential-helpers/LICENSE
  vendor/github.com/docker/docker-credential-helpers/client/client.go
  vendor/github.com/docker/docker-credential-helpers/client/command.go
  vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go
  vendor/github.com/docker/docker-credential-helpers/credentials/error.go
  vendor/github.com/docker/docker-credential-helpers/credentials/helper.go
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/modules.txt
Labels: dependencies, enhancement, size/XXL

#147 docker_container resource mounts support
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  docker/resource_docker_service.go
Labels: size/L

#116 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  README.md
  docker/data_source_docker_registry_image.go
  docker/data_source_docker_registry_image_test.go
  docker/provider.go
  docker/resource_docker_config.go
  docker/resource_docker_config_test.go
  docker/resource_docker_container.go
  docker/resource_docker_container_test.go
  docker/resource_docker_image.go
  docker/resource_docker_image_test.go
  docker/resource_docker_network.go
  docker/resource_docker_network_test.go
  docker/resource_docker_secret.go
  docker/resource_docker_secret_test.go
  docker/resource_docker_service.go
  docker/resource_docker_service_test.go
  docker/resource_docker_volume.go
  docker/resource_docker_volume_test.go
Labels: size/XL

#153 Add ssh protocol (copy)
  docker/config.go
  examples/ssh-protocol/README.md
  examples/ssh-protocol/main.tf
  go.mod
  go.sum
  vendor/github.com/docker/cli/AUTHORS
  vendor/github.com/docker/cli/LICENSE
  vendor/github.com/docker/cli/NOTICE
  vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn.go
  vendor/github.com/docker/cli/cli/connhelper/commandconn/pdeathsig_linux.go
  vendor/github.com/docker/cli/cli/connhelper/commandconn/pdeathsig_nolinux.go
  vendor/github.com/docker/cli/cli/connhelper/commandconn/session_unix.go
  vendor/github.com/docker/cli/cli/connhelper/commandconn/session_windows.go
  vendor/github.com/docker/cli/cli/connhelper/connhelper.go
  vendor/github.com/docker/cli/cli/connhelper/ssh/ssh.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#87 docker_network data source
  docker/data_source_docker_network.go
  docker/data_source_docker_network_test.go
  docker/provider.go
  website/docs/d/docker_network.html.markdown
Labels: documentation, enhancement, size/L

#154 Fixes for flaky tests
  docker/resource_docker_service_funcs.go
  docker/resource_docker_service_test.go
  scripts/runAccTests.sh
Labels: size/M
