Repository terraform-providers/terraform-provider-docker, pull requests merged in 2019-07, with the labels that each got.

#159 Added cross-platform support for generic Docker credential helper.
  docker/provider.go
Labels: size/S

#162 fix website typo / containers / mount vs mounts
  website/docs/r/container.html.markdown
Labels: documentation, size/XS

#165 Updates the docs
  website/docs/index.html.markdown
  website/docs/r/container.html.markdown
Labels: documentation, size/S
