Repository terraform-providers/terraform-provider-docker, pull requests merged in 2019-03, with the labels that each got.

#135 tests: Simplify Dockerfile(s)
  scripts/testing/Dockerfile
  scripts/testing/Dockerfile_v1
  scripts/testing/Dockerfile_v2
  scripts/testing/Dockerfile_v3
  scripts/testing/setup_private_registry.bat
  scripts/testing/setup_private_registry.sh
Labels: size/S

#136 tests: Skip test if swap limit isn't available
  docker/provider_test.go
  docker/resource_docker_container_test.go
Labels: size/XS

#115 Fix container ports issue for asc ordering
  CHANGELOG.md
  docker/resource_docker_container.go
  docker/resource_docker_container_migrate.go
Labels: size/L

#128 Normalize blank port IP's to 0.0.0.0
  docker/resource_docker_container.go
Labels: size/XS

#137 Fix syntax error in docker_service example and make all examples adhere to terraform fmt
  website/docs/r/config.html.markdown
  website/docs/r/container.html.markdown
  website/docs/r/secret.html.markdown
  website/docs/r/service.html.markdown
Labels: documentation, size/XL
