Repository terraform-providers/terraform-provider-docker, pull requests merged in 2020-02, with the labels that each got.

#229 Correct IPAM config read on the data provider
  docker/data_source_docker_network.go
  docker/data_source_docker_network_test.go
Labels: size/S

#234 support to import some docker_container's attributes
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
Labels: size/L

#236 Support to update docker_container
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
Labels: size/M

#241 ci: bumps docker and ubuntu
  .travis.yml
Labels: size/XS

#240 Allow use of `source` file instead of content / content_base64
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  scripts/testacc_cleanup.sh
  scripts/testacc_setup.sh
  website/docs/r/container.html.markdown
Labels: documentation, size/L
