Repository terraform-providers/terraform-provider-docker, pull requests merged in 2020-11, with the labels that each got.

#300 Add support for init process injection for containers.
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  website/docs/r/container.html.markdown
Labels: documentation, size/M

#308 Add security_opts to container config.
  docker/resource_docker_container.go
  docker/resource_docker_container_funcs.go
  docker/resource_docker_container_test.go
  website/docs/r/container.html.markdown
Labels: documentation, size/XS

#320 Treat null workdir as a no-op
  docker/resource_docker_container.go
Labels: size/XS

#318 Treat null user as a no-op
  docker/resource_docker_container.go
Labels: size/XS

#312 Allow healthcheck to be computed as container can specify
  docker/resource_docker_container.go
Labels: size/XS
