Repository terraform-providers/terraform-provider-docker, pull requests merged in 2020-08, with the labels that each got.

#281 Update service.html.markdown
  website/docs/r/service.html.markdown
Labels: documentation, size/M

#278 Typo in container.html.markdown
  website/docs/r/container.html.markdown
Labels: documentation, size/XS

#271 Fix panic to migrate schema of docker_container from v1 to v2
  docker/label_migration.go
  docker/resource_docker_container.go
Labels: size/XS

#274 Fix port objects with the same internal port but different protocol trigger recreation of container
  docker/resource_docker_container.go
Labels: size/XS
