Repository terraform-providers/terraform-provider-docker, pull requests merged in 2020-10, with the labels that each got.

#253 Added complete support for Docker credential helpers
  docker/provider.go
  go.mod
  go.sum
  vendor/github.com/docker/cli/cli/config/configfile/file.go
  vendor/github.com/docker/cli/cli/config/credentials/credentials.go
  vendor/github.com/docker/cli/cli/config/credentials/default_store.go
  vendor/github.com/docker/cli/cli/config/credentials/default_store_darwin.go
  vendor/github.com/docker/cli/cli/config/credentials/default_store_linux.go
  vendor/github.com/docker/cli/cli/config/credentials/default_store_unsupported.go
  vendor/github.com/docker/cli/cli/config/credentials/default_store_windows.go
  vendor/github.com/docker/cli/cli/config/credentials/file_store.go
  vendor/github.com/docker/cli/cli/config/credentials/native_store.go
  vendor/github.com/docker/cli/cli/config/types/authconfig.go
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/modules.txt
Labels: dependencies, size/XL

#293 Resolve #255 by conditionally adding port binding
  docker/resource_docker_container_funcs.go
Labels: size/XS

#251 Prevent provider error if auth config is incomplete
  docker/provider.go
  docker/provider_test.go
Labels: size/S

#292 chore: fix typo
  website/docs/r/container.html.markdown
Labels: documentation, size/XS

#287 updates link syntax
  website/docs/r/container.html.markdown
Labels: documentation, size/XS

#286 documentation updates
  website/docs/index.html.markdown
  website/docs/r/config.html.markdown
  website/docs/r/container.html.markdown
Labels: documentation, size/XS

#245 Update service.html.markdown
  website/docs/r/service.html.markdown
Labels: documentation, size/XS

#297 chore: bump go 115
  .go-version
  .travis.yml
  README.md
  go.mod
  vendor/github.com/docker/cli/cli/command/image/build/context.go
  vendor/modules.txt
Labels: dependencies, size/S
